# Generated by Django 2.0.6 on 2018-06-21 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.BinaryField(max_length=4294967295)),
            ],
            options={
                'db_table': 'reports',
            },
        ),
        migrations.AddField(
            model_name='playbook',
            name='reports',
            field=models.ManyToManyField(to='api.Report'),
        ),
    ]
