# Generated by Django 2.1.1 on 2018-09-03 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.BinaryField(max_length=4294967295)),
            ],
            options={
                'db_table': 'labels',
            },
        ),
        migrations.AddField(
            model_name='playbook',
            name='labels',
            field=models.ManyToManyField(to='api.Label'),
        ),
    ]
