# Generated by Django 2.2.19 on 2021-04-03 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_playbook_controller'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistinctHost',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('latest_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Host')),
            ],
            options={
                'db_table': 'distinct_hosts',
            },
        ),
    ]
