# Generated by Django 2.2.28 on 2022-07-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_result_delegated_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='play',
            name='name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
