# Generated by Django 3.2.15 on 2022-09-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_play_label_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbook',
            name='user',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
