# Generated by Django 3.2.15 on 2022-10-03 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_ara_versions'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='uuid',
            field=models.UUIDField(null=True),
        ),
    ]
