# Generated by Django 3.2.15 on 2022-10-05 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_task_uuid'),
    ]

    # This reverts migration 0011 which bumped the max_length to 512
    # varchar may not be above 255 to keep compatibility with mysql
    # see: https://github.com/ansible-community/ara/issues/265 and
    # https://github.com/ansible-community/ara/issues/185
    operations = [
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='play',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
