# Generated by Django 3.2.15 on 2022-10-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_revert_play_label_name_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playbook',
            name='controller',
            field=models.CharField(default='localhost', max_length=255, null=True),
        ),
    ]
