# Generated by Django 5.2.8 on 2025-11-30 21:45
# django 5.0 changed how uuid fields work with mariadb
# https://codeberg.org/ansible-community/ara/issues/617

import ara.api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_optional_playbook_controller"),
    ]

    operations = [
        migrations.AlterField(
            model_name="play",
            name="uuid",
            field=ara.api.models.Char32UUIDField(),
        ),
        migrations.AlterField(
            model_name="task",
            name="uuid",
            field=ara.api.models.Char32UUIDField(null=True),
        ),
    ]
