# Generated by Django 5.2.9 on 2025-12-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_alter_play_uuid_alter_task_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="deprecations",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="task",
            name="exceptions",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="task",
            name="warnings",
            field=models.JSONField(default=list),
        ),
    ]
