# Generated by Django 5.2.15 on 2026-07-05 20:03
#
# Adds indexes for the query patterns that were previously full table scans,
# grounded in how the UI, CLI and prometheus exporter actually query. Django
# already auto-indexes foreign keys, so detail-page and callback FK lookups were
# already covered; these fill the remaining gaps:
#
# - status on playbooks and tasks
# - (status, changed) and (status, ignore_errors) on results: ara derives
#   the status it displays from these column pairs (ok+changed is shown as
#   "changed", failed+ignore_errors as "ignored"), so the hottest filters
#   on the largest table pair status with one of the two booleans.
# - started + updated on the Duration models (playbooks, plays, tasks,
#   results) and updated on hosts: the two timestamps list views sort by.
# - (playbook, started) and (host, started) on results: serve the FK
#   filter and -started ordering together for the playbook/host results
#   report pages.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_task_deprecations_exceptions_warnings"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="host",
            index=models.Index(fields=["updated"], name="hosts_updated_idx"),
        ),
        migrations.AddIndex(
            model_name="play",
            index=models.Index(fields=["started"], name="plays_started_idx"),
        ),
        migrations.AddIndex(
            model_name="play",
            index=models.Index(fields=["updated"], name="plays_updated_idx"),
        ),
        migrations.AddIndex(
            model_name="playbook",
            index=models.Index(fields=["status"], name="playbooks_status_idx"),
        ),
        migrations.AddIndex(
            model_name="playbook",
            index=models.Index(fields=["started"], name="playbooks_started_idx"),
        ),
        migrations.AddIndex(
            model_name="playbook",
            index=models.Index(fields=["updated"], name="playbooks_updated_idx"),
        ),
        migrations.AddIndex(
            model_name="result",
            index=models.Index(fields=["status", "changed"], name="results_status_changed_idx"),
        ),
        migrations.AddIndex(
            model_name="result",
            index=models.Index(fields=["status", "ignore_errors"], name="results_status_ignore_idx"),
        ),
        migrations.AddIndex(
            model_name="result",
            index=models.Index(fields=["started"], name="results_started_idx"),
        ),
        migrations.AddIndex(
            model_name="result",
            index=models.Index(fields=["updated"], name="results_updated_idx"),
        ),
        migrations.AddIndex(
            model_name="result",
            index=models.Index(fields=["playbook", "started"], name="results_playbook_started_idx"),
        ),
        migrations.AddIndex(
            model_name="result",
            index=models.Index(fields=["host", "started"], name="results_host_started_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["status"], name="tasks_status_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["started"], name="tasks_started_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["updated"], name="tasks_updated_idx"),
        ),
    ]
