# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-27 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.FileField(upload_to='files/%Y/%m/%d/')),
                ('is_playbook', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start', models.DateTimeField(auto_now_add=True, verbose_name='started')),
                ('ended', models.DateTimeField(auto_now=True, verbose_name='ended')),
                ('name', models.CharField(max_length=255)),
                ('facts', models.TextField(blank=True, null=True)),
                ('changed', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('ok', models.IntegerField(default=0)),
                ('skipped', models.IntegerField(default=0)),
                ('unreachable', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start', models.DateTimeField(auto_now_add=True, verbose_name='started')),
                ('ended', models.DateTimeField(auto_now=True, verbose_name='ended')),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start', models.DateTimeField(auto_now_add=True, verbose_name='started')),
                ('ended', models.DateTimeField(auto_now=True, verbose_name='ended')),
                ('path', models.CharField(max_length=255)),
                ('ansible_version', models.CharField(max_length=255)),
                ('parameters', models.TextField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start', models.DateTimeField(auto_now_add=True, verbose_name='started')),
                ('ended', models.DateTimeField(auto_now=True, verbose_name='ended')),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField(blank=True, null=True)),
                ('type', models.CharField(max_length=255)),
                ('playbook_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='api.Playbook')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start', models.DateTimeField(auto_now_add=True, verbose_name='started')),
                ('ended', models.DateTimeField(auto_now=True, verbose_name='ended')),
                ('status', models.CharField(blank=True, choices=[('ok', 'ok'), ('failed', 'failed'), ('skipped', 'skipped'), ('unreachable', 'unreachable')], max_length=11, null=True)),
                ('changed', models.BooleanField(default=False)),
                ('failed', models.BooleanField(default=False)),
                ('skipped', models.BooleanField(default=False)),
                ('unreachable', models.BooleanField(default=False)),
                ('ignore_errors', models.BooleanField(default=False)),
                ('result', models.TextField(blank=True, null=True)),
                ('playbook_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.Playbook')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start', models.DateTimeField(auto_now_add=True, verbose_name='started')),
                ('ended', models.DateTimeField(auto_now=True, verbose_name='ended')),
                ('name', models.TextField(blank=True, null=True)),
                ('action', models.TextField(blank=True, null=True)),
                ('lineno', models.IntegerField()),
                ('tags', models.TextField(blank=True, null=True)),
                ('handler', models.BooleanField()),
                ('playbook_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.Playbook')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='play',
            name='playbook_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='api.Playbook'),
        ),
        migrations.AddField(
            model_name='host',
            name='playbook_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='api.Playbook'),
        ),
        migrations.AddField(
            model_name='file',
            name='playbook_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.Playbook'),
        ),
    ]
