---
- project:
    check:
      jobs:
        - ara-tox-py3
        - ara-tox-linters
        - ara-tox-docs
        - ara-basic-ansible-core-devel:
            voting: false
        - ara-basic-ansible-6
        - ara-basic-ansible-core-2.14
        - ara-basic-ansible-core-2.13
        - ara-basic-ansible-core-2.12
        - ara-basic-ansible-core-2.11
        - ara-basic-ansible-2.9
        - ara-container-images
    gate:
      jobs:
        - ara-tox-py3
        - ara-tox-linters
        - ara-tox-docs
        - ara-basic-ansible-6
        - ara-basic-ansible-core-2.14
        - ara-basic-ansible-core-2.13
        - ara-basic-ansible-core-2.12
        - ara-basic-ansible-core-2.11
        - ara-basic-ansible-2.9
        - ara-container-images
    post:
      jobs:
        - ara-container-images-dockerhub
        - ara-container-images-quayio
