---
- project:
    check:
      jobs:
        - ara-tox-py3
        - ara-tox-linters
        - ara-tox-docs
        - ara-basic-ansible-core-devel:
            voting: false
        - ara-basic-ansible-8
        - ara-basic-ansible-core-2.15
        - ara-basic-ansible-core-2.14
        - ara-container-images
    gate:
      jobs:
        - ara-tox-py3
        - ara-tox-linters
        - ara-tox-docs
        - ara-basic-ansible-8
        - ara-basic-ansible-core-2.15
        - ara-basic-ansible-core-2.14
        - ara-container-images
    post:
      jobs:
        - ara-container-images-dockerhub
        - ara-container-images-quayio
