---
- project:
    check:
      jobs:
        - ara-tox-py3
        - ara-tox-linters
        - ara-tox-docs
        - ara-basic-ansible-core-devel:
            voting: false
        - ara-basic-ansible-5
        - ara-basic-ansible-core-2.12
        - ara-basic-ansible-core-2.11
        - ara-basic-ansible-base-2.10
        - ara-basic-ansible-2.9
        - ara-container-images
    gate:
      jobs:
        - ara-tox-py3
        - ara-tox-linters
        - ara-tox-docs
        - ara-basic-ansible-5
        - ara-basic-ansible-core-2.12
        - ara-basic-ansible-core-2.11
        - ara-basic-ansible-base-2.10
        - ara-basic-ansible-2.9
        - ara-container-images
