- project:
    vars:
      rtd_webhook_id: '49230'
    templates:
      - docs-on-readthedocs
    check:
      jobs:
        - ara-api-distributed-sqlite
        - ara-api-mysql
        - ara-api-postgresql
        - ara-api-fedora-packages:
            voting: false
        - ara-basic-ansible-devel:
            voting: false
        - ara-basic-ansible-2.8
        - ara-basic-ansible-2.7
        - ara-tox-linters
        - ara-tox-py3
    gate:
      jobs:
        - ara-api-distributed-sqlite
        - ara-api-mysql
        - ara-api-postgresql
        - ara-basic-ansible-2.8
        - ara-basic-ansible-2.7
        - ara-tox-linters
        - ara-tox-py3
    post:
      jobs:
        - ara-upload-git-mirror
        - ara-demo
