- project:
    vars:
      rtd_webhook_id: '49230'
    templates:
      - docs-on-readthedocs
    check:
      jobs:
        - ara-server-ansible-integration:
            voting: false
        - tox-py3
        - tox-pep8
    gate:
      jobs:
        - tox-py3
        - tox-pep8
